FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/
RUN pip3 install --break-system-packages --no-cache-dir -r requirements.txt

COPY . /app/
COPY run.sh /run.sh

RUN chmod +x /run.sh

CMD ["/run.sh"]
